/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Login */
        get: operations["login_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Callback */
        get: operations["auth_callback_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/school-years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List School Years */
        get: operations["list_school_years_api_school_years_get"];
        put?: never;
        /** Create School Year */
        post: operations["create_school_year_api_school_years_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/school-years/{school_year_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get School Year */
        get: operations["get_school_year_api_school_years__school_year_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete School Year
         * @description Deleting a school year always means "delete everything under it too"
         *     -- unlike Trinn/SchoolClass deletes elsewhere in this file, there's no
         *     legitimate case where a user wants to delete a school year but keep its
         *     trinn/subjects/activities around (they'd just become orphaned). So this
         *     cascades explicitly, in FK dependency order, rather than relying on the
         *     restrict-by-default behavior used for structural entities.
         */
        delete: operations["delete_school_year_api_school_years__school_year_id__delete"];
        options?: never;
        head?: never;
        /** Update School Year */
        patch: operations["update_school_year_api_school_years__school_year_id__patch"];
        trace?: never;
    };
    "/api/periods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Periods */
        get: operations["list_periods_api_periods_get"];
        put?: never;
        /** Create Period */
        post: operations["create_period_api_periods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/periods/{period_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Period */
        delete: operations["delete_period_api_periods__period_id__delete"];
        options?: never;
        head?: never;
        /** Update Period */
        patch: operations["update_period_api_periods__period_id__patch"];
        trace?: never;
    };
    "/api/trinn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trinn */
        get: operations["list_trinn_api_trinn_get"];
        put?: never;
        /** Create Trinn */
        post: operations["create_trinn_api_trinn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trinn/{trinn_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Trinn */
        delete: operations["delete_trinn_api_trinn__trinn_id__delete"];
        options?: never;
        head?: never;
        /** Update Trinn */
        patch: operations["update_trinn_api_trinn__trinn_id__patch"];
        trace?: never;
    };
    "/api/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Classes */
        get: operations["list_classes_api_classes_get"];
        put?: never;
        /** Create Class */
        post: operations["create_class_api_classes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classes/{class_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Class */
        delete: operations["delete_class_api_classes__class_id__delete"];
        options?: never;
        head?: never;
        /** Update Class */
        patch: operations["update_class_api_classes__class_id__patch"];
        trace?: never;
    };
    "/api/class-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Class Groups */
        get: operations["list_class_groups_api_class_groups_get"];
        put?: never;
        /** Create Class Group */
        post: operations["create_class_group_api_class_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/class-groups/{class_group_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Class Group */
        delete: operations["delete_class_group_api_class_groups__class_group_id__delete"];
        options?: never;
        head?: never;
        /** Update Class Group */
        patch: operations["update_class_group_api_class_groups__class_group_id__patch"];
        trace?: never;
    };
    "/api/teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teachers */
        get: operations["list_teachers_api_teachers_get"];
        put?: never;
        /** Create Teacher */
        post: operations["create_teacher_api_teachers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teachers/{teacher_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Teacher */
        delete: operations["delete_teacher_api_teachers__teacher_id__delete"];
        options?: never;
        head?: never;
        /** Update Teacher */
        patch: operations["update_teacher_api_teachers__teacher_id__patch"];
        trace?: never;
    };
    "/api/teacher-unavailabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teacher Unavailabilities */
        get: operations["list_teacher_unavailabilities_api_teacher_unavailabilities_get"];
        put?: never;
        /** Create Teacher Unavailability */
        post: operations["create_teacher_unavailability_api_teacher_unavailabilities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teacher-unavailabilities/{unavailability_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Teacher Unavailability */
        delete: operations["delete_teacher_unavailability_api_teacher_unavailabilities__unavailability_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teacher-subject-qualifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teacher Subject Qualifications */
        get: operations["list_teacher_subject_qualifications_api_teacher_subject_qualifications_get"];
        put?: never;
        /** Create Teacher Subject Qualification */
        post: operations["create_teacher_subject_qualification_api_teacher_subject_qualifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/teacher-subject-qualifications/{qualification_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Teacher Subject Qualification */
        delete: operations["delete_teacher_subject_qualification_api_teacher_subject_qualifications__qualification_id__delete"];
        options?: never;
        head?: never;
        /** Update Teacher Subject Qualification */
        patch: operations["update_teacher_subject_qualification_api_teacher_subject_qualifications__qualification_id__patch"];
        trace?: never;
    };
    "/api/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subjects */
        get: operations["list_subjects_api_subjects_get"];
        put?: never;
        /** Create Subject */
        post: operations["create_subject_api_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Subject */
        delete: operations["delete_subject_api_subjects__subject_id__delete"];
        options?: never;
        head?: never;
        /** Update Subject */
        patch: operations["update_subject_api_subjects__subject_id__patch"];
        trace?: never;
    };
    "/api/subject-hour-allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subject Hour Allocations */
        get: operations["list_subject_hour_allocations_api_subject_hour_allocations_get"];
        put?: never;
        /** Create Subject Hour Allocation */
        post: operations["create_subject_hour_allocation_api_subject_hour_allocations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subject-hour-allocations/{allocation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Subject Hour Allocation */
        delete: operations["delete_subject_hour_allocation_api_subject_hour_allocations__allocation_id__delete"];
        options?: never;
        head?: never;
        /** Update Subject Hour Allocation */
        patch: operations["update_subject_hour_allocation_api_subject_hour_allocations__allocation_id__patch"];
        trace?: never;
    };
    "/api/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Activities */
        get: operations["list_activities_api_activities_get"];
        put?: never;
        /** Create Activity */
        post: operations["create_activity_api_activities_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activities/{activity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity */
        get: operations["get_activity_api_activities__activity_id__get"];
        put?: never;
        post?: never;
        /** Delete Activity */
        delete: operations["delete_activity_api_activities__activity_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solver-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Solver Settings */
        get: operations["get_solver_settings_api_solver_settings_get"];
        /** Upsert Solver Settings */
        put: operations["upsert_solver_settings_api_solver_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve */
        post: operations["solve_api_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generated-timetables/{generated_timetable_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Generated Timetable */
        post: operations["activate_generated_timetable_api_generated_timetables__generated_timetable_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/school-years/{school_year_id}/timetable/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Active Timetable */
        get: operations["get_active_timetable_api_school_years__school_year_id__timetable_active_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generated-timetables/{generated_timetable_id}/export.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Timetable Excel */
        get: operations["export_timetable_excel_api_generated_timetables__generated_timetable_id__export_xlsx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Zone */
        patch: operations["rename_zone_api_zones_current_patch"];
        trace?: never;
    };
    "/api/zones/current/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Members */
        get: operations["list_members_api_zones_current_members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones/current/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Invitations */
        get: operations["list_invitations_api_zones_current_invitations_get"];
        put?: never;
        /** Create Invitation */
        post: operations["create_invitation_api_zones_current_invitations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones/current/invitations/{invitation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke Invitation */
        delete: operations["revoke_invitation_api_zones_current_invitations__invitation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/zones/current/members/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Member */
        delete: operations["remove_member_api_zones_current_members__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/import/school": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import School */
        post: operations["import_school_api_import_school_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityCreate */
        ActivityCreate: {
            /** School Year Id */
            school_year_id: number;
            activity_type: components["schemas"]["ActivityType"];
            /** Duration Ticks */
            duration_ticks: number;
            /** Occurrences Per Week */
            occurrences_per_week: number;
            /** Notes */
            notes?: string | null;
            /** Legs */
            legs: components["schemas"]["ActivityLegCreate"][];
        };
        /** ActivityImport */
        ActivityImport: {
            activity_type: components["schemas"]["ActivityType"];
            /** Duration Minutes */
            duration_minutes: number;
            /** Occurrences Per Week */
            occurrences_per_week: number;
            /** Notes */
            notes?: string | null;
            /** Legs */
            legs: components["schemas"]["ActivityLegImport"][];
        };
        /** ActivityLegCreate */
        ActivityLegCreate: {
            /** Class Group Id */
            class_group_id?: number | null;
            /** Subject Id */
            subject_id: number;
            /**
             * Teacher Ids
             * @default []
             */
            teacher_ids: number[];
        };
        /** ActivityLegImport */
        ActivityLegImport: {
            /** Class Ref */
            class_ref?: string | null;
            /** Subject Code */
            subject_code: string;
            /**
             * Teacher Initials
             * @default []
             */
            teacher_initials: string[];
        };
        /** ActivityLegRead */
        ActivityLegRead: {
            /** Id */
            id: number;
            /** Class Group Id */
            class_group_id: number | null;
            /** Subject Id */
            subject_id: number;
            /**
             * Teacher Ids
             * @default []
             */
            teacher_ids: number[];
        };
        /** ActivityRead */
        ActivityRead: {
            /** Id */
            id: number;
            /** School Year Id */
            school_year_id: number;
            activity_type: components["schemas"]["ActivityType"];
            /** Duration Ticks */
            duration_ticks: number;
            /** Occurrences Per Week */
            occurrences_per_week: number;
            /** Notes */
            notes?: string | null;
            /**
             * Legs
             * @default []
             */
            legs: components["schemas"]["ActivityLegRead"][];
        };
        /**
         * ActivityType
         * @enum {string}
         */
        ActivityType: "NORMAL" | "SPLIT_PARALLEL" | "TRINNFAG";
        /** ClassGroupCreate */
        ClassGroupCreate: {
            /** School Class Id */
            school_class_id: number;
            /**
             * Label
             * @default whole
             */
            label: string;
        };
        /** ClassGroupRead */
        ClassGroupRead: {
            /** School Class Id */
            school_class_id: number;
            /**
             * Label
             * @default whole
             */
            label: string;
            /** Id */
            id: number;
        };
        /** ClassImport */
        ClassImport: {
            /** Name */
            name: string;
            /**
             * Extra Groups
             * @default []
             */
            extra_groups: string[];
        };
        /**
         * DayOfWeek
         * @enum {string}
         */
        DayOfWeek: "MON" | "TUE" | "WED" | "THU" | "FRI";
        /** GeneratedTimetableRead */
        GeneratedTimetableRead: {
            /** Id */
            id: number;
            /** School Year Id */
            school_year_id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Solver Status */
            solver_status: string;
            /** Objective Value */
            objective_value: number | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Slots
             * @default []
             */
            slots: components["schemas"]["TimetableSlotRead"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourAllocationImport */
        HourAllocationImport: {
            /** Trinn Level */
            trinn_level: number;
            /** Weekly Hours */
            weekly_hours: number;
        };
        /** ImportIssue */
        ImportIssue: {
            /** Path */
            path: string;
            /** Message */
            message: string;
        };
        /** ImportResultRead */
        ImportResultRead: {
            /** School Year Id */
            school_year_id: number;
            /** Counts */
            counts: {
                [key: string]: number;
            };
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["ImportIssue"][];
        };
        /** PeriodDefinitionCreate */
        PeriodDefinitionCreate: {
            /** School Year Id */
            school_year_id: number;
            day_of_week: components["schemas"]["DayOfWeek"];
            /** Period Number */
            period_number: number;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
            /**
             * Is Splittable
             * @default false
             */
            is_splittable: boolean;
            /**
             * Is Before Lunch
             * @default false
             */
            is_before_lunch: boolean;
        };
        /** PeriodDefinitionRead */
        PeriodDefinitionRead: {
            /** School Year Id */
            school_year_id: number;
            day_of_week: components["schemas"]["DayOfWeek"];
            /** Period Number */
            period_number: number;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
            /**
             * Is Splittable
             * @default false
             */
            is_splittable: boolean;
            /**
             * Is Before Lunch
             * @default false
             */
            is_before_lunch: boolean;
            /** Id */
            id: number;
        };
        /** PeriodImport */
        PeriodImport: {
            day_of_week: components["schemas"]["DayOfWeek"];
            /** Period Number */
            period_number: number;
            /**
             * Start Time
             * Format: time
             */
            start_time: string;
            /**
             * End Time
             * Format: time
             */
            end_time: string;
            /**
             * Is Splittable
             * @default false
             */
            is_splittable: boolean;
            /**
             * Is Before Lunch
             * @default false
             */
            is_before_lunch: boolean;
        };
        /** SchoolClassCreate */
        SchoolClassCreate: {
            /** Trinn Id */
            trinn_id: number;
            /** Name */
            name: string;
        };
        /** SchoolClassRead */
        SchoolClassRead: {
            /** Trinn Id */
            trinn_id: number;
            /** Name */
            name: string;
            /** Id */
            id: number;
        };
        /** SchoolImport */
        SchoolImport: {
            /** School Year Label */
            school_year_label: string;
            /**
             * Periods
             * @default []
             */
            periods: components["schemas"]["PeriodImport"][];
            /**
             * Trinn
             * @default []
             */
            trinn: components["schemas"]["TrinnImport"][];
            /**
             * Teachers
             * @default []
             */
            teachers: components["schemas"]["TeacherImport"][];
            /**
             * Subjects
             * @default []
             */
            subjects: components["schemas"]["SubjectImport"][];
            /**
             * Activities
             * @default []
             */
            activities: components["schemas"]["ActivityImport"][];
        };
        /** SchoolYearCreate */
        SchoolYearCreate: {
            /** Label */
            label: string;
        };
        /** SchoolYearRead */
        SchoolYearRead: {
            /** Label */
            label: string;
            /** Id */
            id: number;
        };
        /** SolveRequest */
        SolveRequest: {
            /** School Year Id */
            school_year_id: number;
            /**
             * Time Limit Seconds
             * @default 60
             */
            time_limit_seconds: number;
            /**
             * Optimize
             * @default true
             */
            optimize: boolean;
            /**
             * Variant Count
             * @default 1
             */
            variant_count: number;
        };
        /** SolveResponse */
        SolveResponse: {
            /** Generated Timetable Id */
            generated_timetable_id: number | null;
            /** Status */
            status: string;
            /** Infeasible Sessions */
            infeasible_sessions: string[];
            /** Placement Count */
            placement_count: number;
            /**
             * Variants
             * @default []
             */
            variants: components["schemas"]["VariantSummary"][];
        };
        /** SolverSettingsRead */
        SolverSettingsRead: {
            /** School Year Id */
            school_year_id: number;
            /**
             * Max Concurrent Krov
             * @default 2
             */
            max_concurrent_krov: number;
            /**
             * Preferred Concurrent Krov
             * @default 1
             */
            preferred_concurrent_krov: number;
            /**
             * Krov10 Preferred Periods
             * @default 3,4
             */
            krov10_preferred_periods: string;
            /**
             * Fremmedspraak10 Fixed Day
             * @default WED
             */
            fremmedspraak10_fixed_day: string;
            /**
             * Fremmedspraak10 Fixed Periods
             * @default 5,6
             */
            fremmedspraak10_fixed_periods: string;
            /**
             * Weight Musikk Spread
             * @default 10
             */
            weight_musikk_spread: number;
            /**
             * Weight Matte Before Lunch
             * @default 10
             */
            weight_matte_before_lunch: number;
            /**
             * Weight Mat Helse Placement
             * @default 10
             */
            weight_mat_helse_placement: number;
            /**
             * Weight Krov Prefer One
             * @default 5
             */
            weight_krov_prefer_one: number;
            /**
             * Weight Prefer Early Periods
             * @default 10
             */
            weight_prefer_early_periods: number;
            /**
             * Weight Avoid Friday Afternoon
             * @default 10
             */
            weight_avoid_friday_afternoon: number;
            /** Id */
            id: number;
        };
        /** SolverSettingsUpsert */
        SolverSettingsUpsert: {
            /** School Year Id */
            school_year_id: number;
            /**
             * Max Concurrent Krov
             * @default 2
             */
            max_concurrent_krov: number;
            /**
             * Preferred Concurrent Krov
             * @default 1
             */
            preferred_concurrent_krov: number;
            /**
             * Krov10 Preferred Periods
             * @default 3,4
             */
            krov10_preferred_periods: string;
            /**
             * Fremmedspraak10 Fixed Day
             * @default WED
             */
            fremmedspraak10_fixed_day: string;
            /**
             * Fremmedspraak10 Fixed Periods
             * @default 5,6
             */
            fremmedspraak10_fixed_periods: string;
            /**
             * Weight Musikk Spread
             * @default 10
             */
            weight_musikk_spread: number;
            /**
             * Weight Matte Before Lunch
             * @default 10
             */
            weight_matte_before_lunch: number;
            /**
             * Weight Mat Helse Placement
             * @default 10
             */
            weight_mat_helse_placement: number;
            /**
             * Weight Krov Prefer One
             * @default 5
             */
            weight_krov_prefer_one: number;
            /**
             * Weight Prefer Early Periods
             * @default 10
             */
            weight_prefer_early_periods: number;
            /**
             * Weight Avoid Friday Afternoon
             * @default 10
             */
            weight_avoid_friday_afternoon: number;
        };
        /** SubjectCreate */
        SubjectCreate: {
            /** School Year Id */
            school_year_id: number;
            /** Name */
            name: string;
            /** Short Code */
            short_code: string;
            /**
             * Is Trinnfag
             * @default false
             */
            is_trinnfag: boolean;
            /**
             * Is Krov
             * @default false
             */
            is_krov: boolean;
            /**
             * Uses Hall
             * @default false
             */
            uses_hall: boolean;
            /**
             * Avoid Consecutive
             * @default false
             */
            avoid_consecutive: boolean;
            /**
             * Prefer Before Lunch
             * @default false
             */
            prefer_before_lunch: boolean;
            /**
             * Needs Consecutive Periods
             * @default false
             */
            needs_consecutive_periods: boolean;
            /**
             * Prefer Early Periods
             * @default false
             */
            prefer_early_periods: boolean;
            /**
             * Avoid Friday Afternoon
             * @default false
             */
            avoid_friday_afternoon: boolean;
            /**
             * No Repeat Same Day
             * @default false
             */
            no_repeat_same_day: boolean;
            /** Max Concurrent Sessions */
            max_concurrent_sessions?: number | null;
        };
        /** SubjectHourAllocationCreate */
        SubjectHourAllocationCreate: {
            /** Subject Id */
            subject_id: number;
            /** Trinn Id */
            trinn_id: number;
            /** Weekly Hours */
            weekly_hours: number;
        };
        /** SubjectHourAllocationRead */
        SubjectHourAllocationRead: {
            /** Subject Id */
            subject_id: number;
            /** Trinn Id */
            trinn_id: number;
            /** Weekly Hours */
            weekly_hours: number;
            /** Id */
            id: number;
        };
        /** SubjectImport */
        SubjectImport: {
            /** Short Code */
            short_code: string;
            /** Name */
            name: string;
            /**
             * Is Trinnfag
             * @default false
             */
            is_trinnfag: boolean;
            /**
             * Is Krov
             * @default false
             */
            is_krov: boolean;
            /**
             * Uses Hall
             * @default false
             */
            uses_hall: boolean;
            /**
             * Avoid Consecutive
             * @default false
             */
            avoid_consecutive: boolean;
            /**
             * Prefer Before Lunch
             * @default false
             */
            prefer_before_lunch: boolean;
            /**
             * Needs Consecutive Periods
             * @default false
             */
            needs_consecutive_periods: boolean;
            /**
             * Prefer Early Periods
             * @default false
             */
            prefer_early_periods: boolean;
            /**
             * Avoid Friday Afternoon
             * @default false
             */
            avoid_friday_afternoon: boolean;
            /**
             * No Repeat Same Day
             * @default false
             */
            no_repeat_same_day: boolean;
            /** Max Concurrent Sessions */
            max_concurrent_sessions?: number | null;
            /**
             * Hour Allocations
             * @default []
             */
            hour_allocations: components["schemas"]["HourAllocationImport"][];
        };
        /** SubjectRead */
        SubjectRead: {
            /** School Year Id */
            school_year_id: number;
            /** Name */
            name: string;
            /** Short Code */
            short_code: string;
            /**
             * Is Trinnfag
             * @default false
             */
            is_trinnfag: boolean;
            /**
             * Is Krov
             * @default false
             */
            is_krov: boolean;
            /**
             * Uses Hall
             * @default false
             */
            uses_hall: boolean;
            /**
             * Avoid Consecutive
             * @default false
             */
            avoid_consecutive: boolean;
            /**
             * Prefer Before Lunch
             * @default false
             */
            prefer_before_lunch: boolean;
            /**
             * Needs Consecutive Periods
             * @default false
             */
            needs_consecutive_periods: boolean;
            /**
             * Prefer Early Periods
             * @default false
             */
            prefer_early_periods: boolean;
            /**
             * Avoid Friday Afternoon
             * @default false
             */
            avoid_friday_afternoon: boolean;
            /**
             * No Repeat Same Day
             * @default false
             */
            no_repeat_same_day: boolean;
            /** Max Concurrent Sessions */
            max_concurrent_sessions?: number | null;
            /** Id */
            id: number;
        };
        /** TeacherCreate */
        TeacherCreate: {
            /** Initials */
            initials: string;
            /** Full Name */
            full_name: string;
        };
        /** TeacherImport */
        TeacherImport: {
            /** Initials */
            initials: string;
            /** Full Name */
            full_name: string;
        };
        /** TeacherRead */
        TeacherRead: {
            /** Initials */
            initials: string;
            /** Full Name */
            full_name: string;
            /** Id */
            id: number;
        };
        /** TeacherSubjectQualificationCreate */
        TeacherSubjectQualificationCreate: {
            /** Teacher Id */
            teacher_id: number;
            /** Subject Id */
            subject_id: number;
            /** Weekly Hours */
            weekly_hours?: number | null;
        };
        /** TeacherSubjectQualificationRead */
        TeacherSubjectQualificationRead: {
            /** Teacher Id */
            teacher_id: number;
            /** Subject Id */
            subject_id: number;
            /** Weekly Hours */
            weekly_hours?: number | null;
            /** Id */
            id: number;
        };
        /** TeacherSubjectQualificationUpdate */
        TeacherSubjectQualificationUpdate: {
            /** Weekly Hours */
            weekly_hours?: number | null;
        };
        /** TeacherUnavailabilityCreate */
        TeacherUnavailabilityCreate: {
            /** Teacher Id */
            teacher_id: number;
            /** School Year Id */
            school_year_id: number;
            day_of_week: components["schemas"]["DayOfWeek"];
            /** Start Period */
            start_period?: number | null;
            /** End Period */
            end_period?: number | null;
        };
        /** TeacherUnavailabilityRead */
        TeacherUnavailabilityRead: {
            /** Teacher Id */
            teacher_id: number;
            /** School Year Id */
            school_year_id: number;
            day_of_week: components["schemas"]["DayOfWeek"];
            /** Start Period */
            start_period?: number | null;
            /** End Period */
            end_period?: number | null;
            /** Id */
            id: number;
        };
        /** TimetableSlotRead */
        TimetableSlotRead: {
            /** Id */
            id: number;
            /** Activity Id */
            activity_id: number;
            /** Occurrence Index */
            occurrence_index: number;
            day_of_week: components["schemas"]["DayOfWeek"];
            /** Start Tick */
            start_tick: number;
            /** Duration Ticks */
            duration_ticks: number;
        };
        /** TrinnCreate */
        TrinnCreate: {
            /** School Year Id */
            school_year_id: number;
            /** Level */
            level: number;
        };
        /** TrinnImport */
        TrinnImport: {
            /** Level */
            level: number;
            /**
             * Classes
             * @default []
             */
            classes: components["schemas"]["ClassImport"][];
        };
        /** TrinnRead */
        TrinnRead: {
            /** School Year Id */
            school_year_id: number;
            /** Level */
            level: number;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VariantSummary */
        VariantSummary: {
            /** Generated Timetable Id */
            generated_timetable_id: number;
            /** Status */
            status: string;
            /** Placement Count */
            placement_count: number;
            /** Is Active */
            is_active: boolean;
        };
        /** ZoneInvitationCreate */
        ZoneInvitationCreate: {
            /** Email */
            email: string;
        };
        /** ZoneInvitationRead */
        ZoneInvitationRead: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ZoneMemberRead */
        ZoneMemberRead: {
            /** User Id */
            user_id: number;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /**
             * Joined At
             * Format: date-time
             */
            joined_at: string;
        };
        /** ZoneRename */
        ZoneRename: {
            /** Name */
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    auth_callback_auth_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_school_years_api_school_years_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolYearRead"][];
                };
            };
        };
    };
    create_school_year_api_school_years_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchoolYearCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolYearRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_school_year_api_school_years__school_year_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                school_year_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolYearRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_school_year_api_school_years__school_year_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                school_year_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_school_year_api_school_years__school_year_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                school_year_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchoolYearCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolYearRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_periods_api_periods_get: {
        parameters: {
            query: {
                school_year_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodDefinitionRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_period_api_periods_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeriodDefinitionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodDefinitionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_period_api_periods__period_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                period_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_period_api_periods__period_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                period_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeriodDefinitionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodDefinitionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trinn_api_trinn_get: {
        parameters: {
            query: {
                school_year_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrinnRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_trinn_api_trinn_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrinnCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrinnRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trinn_api_trinn__trinn_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trinn_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trinn_api_trinn__trinn_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trinn_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrinnCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrinnRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_classes_api_classes_get: {
        parameters: {
            query: {
                trinn_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolClassRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_class_api_classes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchoolClassCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolClassRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_class_api_classes__class_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_class_api_classes__class_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchoolClassCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolClassRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_class_groups_api_class_groups_get: {
        parameters: {
            query: {
                school_class_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassGroupRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_class_group_api_class_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_class_group_api_class_groups__class_group_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_group_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_class_group_api_class_groups__class_group_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                class_group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teachers_api_teachers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherRead"][];
                };
            };
        };
    };
    create_teacher_api_teachers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_teacher_api_teachers__teacher_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teacher_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_teacher_api_teachers__teacher_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teacher_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teacher_unavailabilities_api_teacher_unavailabilities_get: {
        parameters: {
            query: {
                teacher_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherUnavailabilityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_teacher_unavailability_api_teacher_unavailabilities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherUnavailabilityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherUnavailabilityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_teacher_unavailability_api_teacher_unavailabilities__unavailability_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                unavailability_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_teacher_subject_qualifications_api_teacher_subject_qualifications_get: {
        parameters: {
            query: {
                teacher_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherSubjectQualificationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_teacher_subject_qualification_api_teacher_subject_qualifications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherSubjectQualificationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherSubjectQualificationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_teacher_subject_qualification_api_teacher_subject_qualifications__qualification_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qualification_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_teacher_subject_qualification_api_teacher_subject_qualifications__qualification_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                qualification_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeacherSubjectQualificationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeacherSubjectQualificationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subjects_api_subjects_get: {
        parameters: {
            query: {
                school_year_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subject_api_subjects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subject_api_subjects__subject_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subject_api_subjects__subject_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                subject_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subject_hour_allocations_api_subject_hour_allocations_get: {
        parameters: {
            query: {
                subject_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectHourAllocationRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subject_hour_allocation_api_subject_hour_allocations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectHourAllocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectHourAllocationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_subject_hour_allocation_api_subject_hour_allocations__allocation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                allocation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subject_hour_allocation_api_subject_hour_allocations__allocation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                allocation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectHourAllocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectHourAllocationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_activities_api_activities_get: {
        parameters: {
            query: {
                school_year_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_activity_api_activities_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivityCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_api_activities__activity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_activity_api_activities__activity_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                activity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_solver_settings_api_solver_settings_get: {
        parameters: {
            query: {
                school_year_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolverSettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_solver_settings_api_solver_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolverSettingsUpsert"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolverSettingsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_api_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_generated_timetable_api_generated_timetables__generated_timetable_id__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generated_timetable_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VariantSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_active_timetable_api_school_years__school_year_id__timetable_active_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                school_year_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GeneratedTimetableRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_timetable_excel_api_generated_timetables__generated_timetable_id__export_xlsx_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                generated_timetable_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_zone_api_zones_current_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneRename"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_members_api_zones_current_members_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneMemberRead"][];
                };
            };
        };
    };
    list_invitations_api_zones_current_invitations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneInvitationRead"][];
                };
            };
        };
    };
    create_invitation_api_zones_current_invitations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneInvitationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneInvitationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_invitation_api_zones_current_invitations__invitation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_member_api_zones_current_members__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_school_api_import_school_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchoolImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResultRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
