"""initial schema

Revision ID: f40b44769774
Revises: 
Create Date: 2026-07-07 20:05:51.031834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f40b44769774'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initials', sa.String(length=10), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initials')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.Enum('NORMAL', 'SPLIT_PARALLEL', 'TRINNFAG', name='activitytype'), nullable=False),
    sa.Column('duration_ticks', sa.Integer(), nullable=False),
    sa.Column('occurrences_per_week', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('solver_status', sa.String(length=20), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('period_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', name='dayofweek'), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_splittable', sa.Boolean(), nullable=False),
    sa.Column('is_before_lunch', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_year_id', 'day_of_week', 'period_number')
    )
    op.create_table('solver_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('max_concurrent_krov', sa.Integer(), nullable=False),
    sa.Column('preferred_concurrent_krov', sa.Integer(), nullable=False),
    sa.Column('krov10_preferred_periods', sa.String(length=50), nullable=False),
    sa.Column('fremmedspraak10_fixed_day', sa.String(length=3), nullable=False),
    sa.Column('fremmedspraak10_fixed_periods', sa.String(length=50), nullable=False),
    sa.Column('weight_musikk_spread', sa.Integer(), nullable=False),
    sa.Column('weight_matte_before_lunch', sa.Integer(), nullable=False),
    sa.Column('weight_mat_helse_placement', sa.Integer(), nullable=False),
    sa.Column('weight_krov_prefer_one', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_year_id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('is_trinnfag', sa.Boolean(), nullable=False),
    sa.Column('is_krov', sa.Boolean(), nullable=False),
    sa.Column('uses_hall', sa.Boolean(), nullable=False),
    sa.Column('avoid_consecutive', sa.Boolean(), nullable=False),
    sa.Column('prefer_before_lunch', sa.Boolean(), nullable=False),
    sa.Column('needs_consecutive_periods', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_year_id', 'short_code')
    )
    op.create_table('teacher_unavailabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', name='dayofweek'), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=True),
    sa.Column('end_period', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trinn',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['school_years.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_year_id', 'level')
    )
    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trinn_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['trinn_id'], ['trinn.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trinn_id', 'name')
    )
    op.create_table('subject_hour_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('trinn_id', sa.Integer(), nullable=False),
    sa.Column('weekly_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['trinn_id'], ['trinn.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'trinn_id')
    )
    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('generated_timetable_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_index', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', name='dayofweek'), nullable=False),
    sa.Column('start_tick', sa.Integer(), nullable=False),
    sa.Column('duration_ticks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['generated_timetable_id'], ['generated_timetables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('class_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_class_id', 'label')
    )
    op.create_table('activity_legs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('class_group_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['class_group_id'], ['class_groups.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_leg_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_leg_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_leg_id'], ['activity_legs.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_leg_teachers')
    op.drop_table('activity_legs')
    op.drop_table('class_groups')
    op.drop_table('timetable_slots')
    op.drop_table('subject_hour_allocations')
    op.drop_table('school_classes')
    op.drop_table('trinn')
    op.drop_table('teacher_unavailabilities')
    op.drop_table('subjects')
    op.drop_table('solver_settings')
    op.drop_table('period_definitions')
    op.drop_table('generated_timetables')
    op.drop_table('activities')
    op.drop_table('users')
    op.drop_table('teachers')
    op.drop_table('school_years')
    # ### end Alembic commands ###
